# Generated by Django 3.1.2 on 2020-12-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_data',
            old_name='Email',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='customer_data',
            name='gender',
            field=models.TextField(default='', max_length=6),
        ),
    ]
