# Generated by Django 3.1.2 on 2020-12-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201221_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_data',
            name='status',
            field=models.TextField(default='', max_length=20),
        ),
    ]
