# Generated by Django 3.1.2 on 2020-12-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customer_data_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us_data',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
