# Generated by Django 3.1.2 on 2021-01-22 08:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_contact_us_data_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default='')),
                ('created_at', models.DateTimeField(default='')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer_data')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.product_data')),
            ],
        ),
    ]
