# Generated by Django 3.1.2 on 2021-01-22 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='cart_data',
        ),
    ]
