# Generated by Django 3.1.2 on 2021-01-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210122_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_data',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
