# Generated by Django 3.1.2 on 2021-01-29 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_reply_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(default='', max_length=500)),
                ('blog_desc', models.TextField(default='', max_length=5000)),
                ('image', models.ImageField(upload_to='')),
                ('like', models.IntegerField(default='')),
                ('created_at', models.DateTimeField(default='')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
