# Generated by Django 3.1.2 on 2021-02-24 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_blog_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_name', models.CharField(default='', max_length=500)),
                ('amount', models.FloatField(default='')),
                ('validate_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default='')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
