# Generated by Django 3.1.2 on 2021-02-24 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_discount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='discount',
            new_name='discount_data',
        ),
    ]
