# Generated by Django 3.1.2 on 2021-02-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210224_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_data',
            name='qty',
        ),
    ]
