# Generated by Django 3.1.2 on 2021-03-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_cart_data_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_data',
            name='o_date',
        ),
        migrations.AddField(
            model_name='order_data',
            name='order_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order_data',
            name='status',
            field=models.TextField(default='', max_length=20),
        ),
    ]
