# Generated by Django 3.1.2 on 2021-03-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210321_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_data',
            name='payment_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payment_data',
            name='signature',
            field=models.CharField(default='', max_length=100),
        ),
    ]
