# Generated by Django 3.1.2 on 2021-03-25 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20210325_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_data',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.customer_data'),
        ),
    ]
