# Generated by Django 3.1.2 on 2021-03-25 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20210325_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_data',
            old_name='user',
            new_name='user_id',
        ),
    ]
