# Generated by Django 3.1.2 on 2021-03-30 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0018_auto_20210325_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='amount_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default='')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.product_data')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.payment_data')),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
