# Generated by Django 3.1.2 on 2021-03-30 12:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0019_amount_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='amount_data',
            new_name='account_data',
        ),
    ]
