# Generated by Django 3.1.2 on 2021-03-31 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20210330_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='area_data',
        ),
    ]
