# Generated by Django 3.1.2 on 2021-04-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_delete_area_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_data',
            name='p_id',
            field=models.CharField(default='', max_length=500),
        ),
    ]
