# Generated by Django 3.1.2 on 2021-04-01 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20210401_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_data',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.product_data'),
        ),
        migrations.AlterField(
            model_name='account_data',
            name='payment_id',
            field=models.CharField(default='', max_length=500),
        ),
    ]
