# Generated by Django 3.1.2 on 2021-04-07 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20210401_1942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog_data',
        ),
    ]
