# Generated by Django 3.1.2 on 2021-04-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_delete_blog_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gallery_data',
        ),
    ]
