# Generated by Django 3.1.2 on 2021-04-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_delete_gallery_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_data',
            name='image',
            field=models.ImageField(default='avatar5.png', upload_to=''),
        ),
    ]
