# Generated by Django 3.1.2 on 2021-04-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20210411_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_data',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
