# Generated by Django 3.1.5 on 2021-05-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_cart_data_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_data',
            name='order_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
