# Generated by Django 3.1.5 on 2021-05-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_cart_data_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_data',
            name='order_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
