# Generated by Django 3.1.5 on 2021-05-07 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_auto_20210507_0938'),
    ]

    operations = [
        migrations.DeleteModel(
            name='account_data',
        ),
    ]
